import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';
import { Navbar, Sidebar } from '../components';
import ThemeProvider from '../components/ThemeProvider';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: replace with real auth logic
  const isLoggedIn = false;

  // read cookie at request-time so server-rendered HTML can include the right theme class
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('zenite.theme')?.value;
  const htmlClass = themeCookie === 'dark' ? 'dark' : '';

  return (
    <html lang="en" className={htmlClass}>
      <head>
        {/* Run before React hydration to apply the saved theme immediately */}
        <Script id="theme-init" strategy="beforeInteractive">
          {`(function(){try{var t=localStorage.getItem('zenite.theme');if(t==='dark')document.documentElement.classList.add('dark');else document.documentElement.classList.remove('dark')}catch(e){} })()`}
        </Script>
      </head>

      <body className={`font-vend bg-white text-slate-900 dark:bg-gray-900 dark:text-white`}>
        <ThemeProvider>
          <Navbar />
          <div className="flex">
            <Sidebar isLoggedIn={isLoggedIn} />
            <main className="flex-1 p-6">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
