import type { Metadata } from 'next';
import './globals.css';
import { Navbar, Sidebar } from '../components';
import ThemeProvider from '../components/ThemeProvider';
import useThemeStore from '../lib/themeStore';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: replace with real auth logic
  const isLoggedIn = false;

  return (
    <html lang="en">
      <body className={`font-vend`}>
        <ThemeProvider>
          <Navbar />
          <div className="flex">
            <Sidebar isLoggedIn={isLoggedIn} />
            <main className="flex-1 p-6">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
