name: Secret scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run secret scan
        run: |
          chmod +x ./scripts/secret-scan.sh || true
          ./scripts/secret-scan.sh

